export const services = [
  {
    id: 1,
    heading: "Brand Strategy",
    description:
      "With the support of our global team of experts, we will propose a unique solution, tailored to your business challenge. Brand Institute offers a suite of brand strategy services to complement our naming, market research, design and regulatory capabilities. These services enable our clients to make insight- and data-driven decisions to build their brands, expand their portfolio and grow their company in a competitive marketplace where disruptive innovation, brand acquisition and complexity are on the rise.",
  },
  {
    id: 2,
    heading: "Creative Nomenclature Development",
    description:
      "A unique name is the foundation of your brand’s identity. It is the foremost branding element that your customers will recall and associate with your product, service or company. Brand Institute has created more brand names than any company in the world. This experience, coupled with our responsive service and innovative technologies, will drive your project to a successful conclusion and a great brand name.",
  },
  {
    id: 3,
    heading: "Market Research",
    description:
      "Successful brands convey a sense of trust and reliability through inherent core values which, over time, build brand loyalty and equity. Market Research experts can create fully customizable qualitative and quantitative surveys to fit your needs.",
  },
  {
    id: 4,
    heading: "Regulatory",
    description:
      "Drug Safety Institute (DSI), a subsidiary of Brand Institute, was created in 2004. DSI is dedicated to improving the safe use of Pharmaceuticals by providing a global, state-of-the-art research model for proprietary (brand and line extension) and nonproprietary (USAN/INN) nomenclature research.",
  },
  {
    id: 5,
    heading: "Trademarks",
    description:
      "Brand Institute is the only brand identity consultancy that has in-house trademark attorneys and paralegals to partner and assist your attorneys in this crucial stage of name development.  Having an in-house legal team helps maintain confidentiality, accuracy, timeliness, and consistency; and the value of our trademark services are unparalleled in the industry.",
  },
  {
    id: 6,
    heading: "Visual Identity",
    description:
      "Our expertise in the field of nomenclature development with a seasoned team of graphic designers to create a coherent and resonant visual identity. Our methodology focuses on consistency across all marketing materials, from packaging to key components of sales and merchandising. An exceptionally-executed logo and visual identity have the power to differentiate your brand in today’s competitive marketplace.",
  },
];

export const experience = [
  {
    healthcare: [
      {
        id: 1,
        img: "https://www.brandinstitute.com/images/logos/eylea.jpg",
        category: "Rx",
        name: "Regeneron",
      },
      {
        id: 2,
        img: "https://www.brandinstitute.com/wp-content/uploads/2019/10/coolsculpting-e1576001899518.jpg",
        category: "Medical Device",
        name: "Allergan",
      },
      {
        id: 3,
        img: "	https://www.brandinstitute.com/wp-content/uploads/2019/10/acuvue-e1576001877642.jpg",
        category: "Consumer Health",
        name: "Johnson & Johnson",
      },
      {
        id: 4,
        img: "	https://www.brandinstitute.com/wp-content/uploads/2019/10/cologuard-e1576001907250.jpg",
        category: "Diagnostic",
        name: "Exact Sciences",
      },
      {
        id: 5,
        img: "https://www.brandinstitute.com/wp-content/uploads/2019/10/advil-e1576001869236.jpg",
        category: "OTC",
        name: "Pfizer",
      },
      {
        id: 6,
        img: "https://www.brandinstitute.com/wp-content/uploads/2019/10/odyssey-e1576001892261.jpg",
        category: "Clinical Trial",
        name: "Regeneron",
      },
    ],
  },
  {
    consumer: [
      {
        id: 1,
        img: "https://www.brandinstitute.com/wp-content/uploads/2019/11/aquafina_-e1576001846691.jpg",
        category: "Beverages",
        name: "Aquafina",
      },
      {
        id: 2,
        img: "https://www.brandinstitute.com/wp-content/uploads/2019/11/crunchwrap-e1576001838822.jpg",
        category: "Food",
        name: "CrunchWrap Supreme",
      },
      {
        id: 3,
        img: "	https://www.brandinstitute.com/wp-content/uploads/2019/11/hyundai-e1576001829746.jpg",
        category: "Automotive",
        name: "Hyundai Palisade",
      },
      {
        id: 4,
        img: "https://www.brandinstitute.com/wp-content/uploads/2019/11/IdeaPad-e1576001821212.jpg",
        category: "Technology",
        name: "IdeaPad",
      },
      {
        id: 5,
        img: "https://www.brandinstitute.com/wp-content/uploads/2019/11/magnifique-e1576001812218.jpg",
        category: "Personal Products",
        name: "Magnifique",
      },
      {
        id: 6,
        img: "https://www.brandinstitute.com/wp-content/uploads/2019/11/wildfrontier-e1576001804518.jpg",
        category: "Pet Products",
        name: "Wild Frontier",
      },
    ],
  },
  {
    corporate: [
      {
        id: 1,
        img: "	https://www.brandinstitute.com/wp-content/uploads/2019/11/att_-e1576001796301.jpg",
        category: "Telecommunication",
        name: "AT&T Wireless",
      },
      {
        id: 2,
        img: "	https://www.brandinstitute.com/wp-content/uploads/2019/11/exterran_-e1576001787921.jpg",
        category: "Oil & Gas",
        name: "Exterran",
      },
      {
        id: 3,
        img: "https://www.brandinstitute.com/wp-content/uploads/2019/11/infoprint_-e1576001779927.jpg",
        category: "Technology",
        name: "InfoPrint Solutions",
      },
      {
        id: 4,
        img: "	https://www.brandinstitute.com/wp-content/uploads/2019/11/intellus_-e1576001770310.jpg",
        category: "Business Services",
        name: "Intellus Worldwide ",
      },
      {
        id: 5,
        img: "	https://www.brandinstitute.com/wp-content/uploads/2019/11/sunovion_-e1576001760895.jpg",
        category: "Healthcare",
        name: "Sunovion",
      },
      {
        id: 6,
        img: "https://www.brandinstitute.com/wp-content/uploads/2019/11/stage6_-e1576001745316.jpg",
        category: "Entertainment",
        name: "Stage 6",
      },
    ],
  },
];

export const Cities = [
  {
    id: 1,
    img: "https://www.brandinstitute.com/wp-content/uploads/2019/11/basel2.jpg",
    cityname: "Basel",
    address: "Innere Margarethenstrasse 54051 Basel, Switzerland",
    phone: "+41-78-879-4619",
    email: "press@brandinstitute.com",
    team: "",
  },
  {
    id: 2,
    img: "https://www.brandinstitute.com/wp-content/uploads/2019/11/boston2.jpg",
    cityname: "Boston",
    address: "855 Boylston St, 10th Floor Boston, MA 02116",
    phone: "+1 (781) 602-6044",
    email: "boston@brandinstitute.com",
    team: "https://www.brandinstitute.com/bios/03-BOSTON-TEAM.pdf",
  },
  {
    id: 3,
    img: "	https://www.brandinstitute.com/wp-content/uploads/2019/11/chicago.jpg",
    cityname: "Chicago",
    address: "5250 Old Orchard Drive Suite 300 Skokie, IL 60077",
    phone: "+1 (312) 475-9600",
    email: "ChicagoGroup@brandinstitute.com",
    team: "https://www.brandinstitute.com/bios/04-CHICAGO-TEAM.pdf",
  },
  {
    id: 4,
    img: "	https://www.brandinstitute.com/wp-content/uploads/2019/11/dallas.jpg",
    cityname: "Dallas",
    address: "7700 Windrose Avenue Suite G300 Plano, TX 75024",
    phone: "+1 (512) 369-9100",
    email: "DallasGroup@brandinstitute.com",
    team: "https://www.brandinstitute.com/bios/05-DALLAS-TEAM.pdf",
  },
  {
    id: 5,
    img: "https://www.brandinstitute.com/wp-content/uploads/2019/11/boston2.jpg",
    cityname: "Frankfurt",
    address:
      "Ecos Office Center Wiesbaden Klingholzstr. 7D-65189 Wiesbaden, Germany",
    phone: "++49 611 97774-563",
    email: "frankfurt@brandinstitute.com",
    team: "https://www.brandinstitute.com/bios/07-FRANKFURT-TEAM.pdf",
  },
  {
    id: 6,
    img: "https://www.brandinstitute.com/wp-content/uploads/2019/11/London.jpg",
    cityname: "London",
    address: "1 Kingdom Street London W2 6BD",
    phone: "+44-7896-875-113",
    email: "LondonGroup@brandinstitute.com",
    team: "https://www.brandinstitute.com/bios/london.asp?dir=00001&email=WEBSITE",
  },
  {
    id: 7,
    img: "https://www.brandinstitute.com/wp-content/uploads/2019/11/losangeles.jpg",
    cityname: "Los Angeles",
    address: "400 Corporate Pointe Suite 300 Culver City, California 90230",
    phone: "+1 (310) 830-6111",
    email: "LosAngelesGroup@brandinstitute.com",
    team: "https://www.brandinstitute.com/bios/la.asp?dir=00001&email=WEBSITE",
  },
  {
    id: 8,
    img: "./assets/creative-startup/img/Miami.jpg",
    cityname: "Miami",
    address: "200 SE 1st Street – 12th Floor Miami, FL 33131",
    phone: "+1 (305) 374-2500",
    email: "press@brandinstitute.com",
    team: "",
  },
  {
    id: 9,
    img: "	https://www.brandinstitute.com/wp-content/uploads/2019/11/seattle.jpg",
    cityname: "Montreal",
    address: "855 Boylston St, 10th Floor Boston, MA 02116",
    phone: "(438) 686-7868",
    email: "press@brandinstitute.com",
    team: "",
  },
  {
    id: 10,
    img: "https://www.brandinstitute.com/wp-content/uploads/2019/11/newyork.jpg",
    cityname: "New York",
    address: "42 Broadway Suite 1700 New York, NY 10004",
    phone: "+1 (212) 557-2100",
    email: "press@brandinstitute.com",
    team: "",
  },
  {
    id: 11,
    img: "https://www.brandinstitute.com/wp-content/uploads/2019/11/mumbai.jpg",
    cityname: "Mumbai",
    address: "855 Boylston St, 10th Floor Boston, MA 02116",
    phone: "(800) 527-2637",
    email: "press@brandinstitute.com",
    team: "",
  },
  {
    id: 12,
    img: "	https://www.brandinstitute.com/wp-content/uploads/2019/11/ottawa.jpg",
    cityname: "Ottawa",
    address: "7 Cypress Gardens, Ottawa, ON, K2S 1W5",
    phone: "+1 (613) 404-7540",
    email: "press@brandinstitute.com",
    team: "",
  },
  {
    id: 13,
    img: "	https://www.brandinstitute.com/wp-content/uploads/2019/11/raleigh.jpg",
    cityname: "Raleigh-Dhuram",
    address: "4819 Emperor Blvd Suite 400 Durham, NC 27703",
    phone: "+1 (919) 572-9311",
    email: "RaleighGroup@brandinstitute.com",
    team: "https://www.brandinstitute.com/bios/durham.asp?dir=00001&email=WEBSITE",
  },
  {
    id: 14,
    img: "	https://www.brandinstitute.com/wp-content/uploads/2019/11/rockville.jpg",
    cityname: "Rockville",
    address: "199 E. Montgomery Avenue Suite 100 Rockville, MD 20850",
    phone: "+1 (301) 984-1055",
    email: "press@brandinstitute.com",
    team: "",
  },
  {
    id: 15,
    img: "https://www.brandinstitute.com/wp-content/uploads/2019/11/sanfrancisco.jpg",
    cityname: "San Francisco",
    address: "611 Gateway Blvd Suite 200 South San Francisco, CA 94080",
    phone: "+1 (415) 421-3200",
    email: "sfgroup@brandinstitute.com",
    team: "https://www.brandinstitute.com/bios/sf.asp?dir=00001&email=WEBSITE",
  },
  {
    id: 16,
    img: "https://www.brandinstitute.com/wp-content/uploads/2019/11/sanjuan.jpg",
    cityname: "San Juan",
    address:
      "Metro Office Park 7 Street 1, Suite 204 Guaynabo, Puerto Rico 00968",
    phone: "+1 (787) 968-3007",
    email: "press@brandinstitute.com",
    team: "",
  },
  {
    id: 17,
    img: "https://www.brandinstitute.com/wp-content/uploads/2019/11/saopaulo.jpg",
    cityname: "São Paulo",
    address:
      "Avenida Paulista, 1079 Conj. 808 Bela Vista CEP 01310-100 São Paulo, Brasil",
    phone: "+55 (11) 945-364-083",
    email: "press@brandinstitute.com",
    team: "",
  },
  {
    id: 18,
    img: "https://www.brandinstitute.com/wp-content/uploads/2019/11/seoul.jpg",
    cityname: "Seoul",
    address:
      "20th Fl., Glass Tower 534 Teheranro, Gangnam-gu, Seoul, 06181, Republic of Korea",
    phone: "+82-10-8000-4842",
    email: "Seoul@brandinstitute.com",
    team: "https://www.brandinstitute.com/bios/seoul.asp?dir=00001&email=WEBSITE",
  },
  {
    id: 19,
    img: "https://www.brandinstitute.com/wp-content/uploads/2019/11/tokyo.jpg",
    cityname: "Tokyo",
    address: "5-1 Nihonbashi Kabuto-cho Chuo-ku Tokyo Japan 1030026",
    phone: "+81-80-6688-6653",
    email: "TokyoGroup@brandinstitute.com",
    team: "https://www.brandinstitute.com/bios/tokyo.asp?dir=00001&email=WEBSITE",
  },
  {
    id: 20,
    img: "	https://www.brandinstitute.com/wp-content/uploads/2019/11/toronto.jpg",
    cityname: "Toronto",
    address: "10 Four Seasons Place Etobicoke, Ontario M9B 6H7",
    phone: "+1 (416) 622-5777",
    email: "TorontoGroup@brandinstitute.com",
    team: "https://www.brandinstitute.com/bios/toronto.asp?dir=00001&email=WEBSITE",
  },
];
